---

- name: LAMP stack setup
  hosts: clients-c
  become: true

  tasks:
      - name: Install Apache
        yum:
            name: httpd
            state: latest

      - name: Make index.html
        copy:
            src: /home/ansible/playbooks/index.html
            dest: /var/www/html/index.html

      - name: Enable Apache
        service:
            name: httpd
            enabled: true

      - name: Start firewalld
        service:
            name: firewalld
            state: started
            enabled: yes


      - name: Add Firewall Exception
        firewalld:
            port: 80/tcp
            permanent: true
            immediate: true
            state: enabled

      - name: Install PHP
        yum:
            name: php
            state: latest

      - name: Download sources
        get_url:
            url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
            dest: .
      
      - name: Install package
        yum:
            name: ./mysql-community-release-el7-5.noarch.rpm
            state: present


      - name: Install MySQL
        yum:
            name: mysql-server
            state: installed

      - name: Start the MYSQL service
        service:
            name: mysqld
            enabled: yes
            state: started